name: Release on Merge to Main

on:
  push:
    branches:
      - main
      - test-branch
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install GCC for Windows target
        run: sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Extract version from Cargo.toml
        id: extract_version
        run: echo "VERSION=$(grep ^version Cargo.toml | sed -E 's/version = \"(.*)\"/v\1/')" >> $GITHUB_ENV

      - name: Build for Linux
        run: cargo build --release

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v3
        with:
          name: lean_http-linux
          path: target/release/lean_http

      - name: Set up Rust for Windows
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu

      - name: Build for Windows
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v3
        with:
          name: lean_http-windows
          path: target/x86_64-pc-windows-gnu/release/lean_http.exe

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: "Descrição da release para a versão ${{ env.VERSION }}."
          files: |
            target/release/lean_http
            target/x86_64-pc-windows-gnu/release/lean_http.exe
        env:
          GITHUB_TOKEN: ${{ secrets.LEAN_HTTP_ACCESS_TOKEN }}
