name: Release on Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Extract version from src/version/version.go
        id: extract_version
        run: |
          VERSION=$(grep 'var Version' src/version/version.go | sed -E 's/.*"([^"]+)".*/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build for Linux
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
          go build -ldflags="-X 'src/version.Version=${{ env.VERSION }}'" -o bin/lean_http

      - name: Upload Linux Binary
        uses: actions/upload-artifact@v3
        with:
          name: lean_http-linux
          path: bin/lean_http

      - name: Build for Windows
        run: |
          mkdir -p bin
          GOOS=windows GOARCH=amd64 CGO_ENABLED=0 \
          go build -ldflags="-X 'src/version.Version=${{ env.VERSION }}'" -o bin/lean_http.exe

      - name: Upload Windows Binary
        uses: actions/upload-artifact@v3
        with:
          name: lean_http-windows
          path: bin/lean_http.exe

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            ## Changelog
            - Esta release inclui as alterações do [Pull Request #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) para a branch `main`.
            
            ### Detalhes
            - Autor: ${{ github.event.pull_request.user.login }}
            - Título: ${{ github.event.pull_request.title }}
            - Data: ${{ github.event.pull_request.merged_at }}

            ### Artefatos
            Inclui os binários compilados para Linux e Windows.
          files: |
            bin/lean_http
            bin/lean_http.exe
        env:
          GITHUB_TOKEN: ${{ secrets.LEAN_HTTP_ACCESS_TOKEN }}
